/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2023-08-27 19:45:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.helper.UserModel;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/pages/../tiles/inc.jsp", Long.valueOf(1692884008000L));
    _jspx_dependants.put("/pages/../tiles/footer_inc.jsp", Long.valueOf(1692766934000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.helper.UserModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Cradle of Life</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- <link rel=\"manifest\" href=\"site.webmanifest\"> -->\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/img/favicon.png\">\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS here -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/owl.carousel.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/magnific-popup.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/font-awesome.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/themify-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/nice-select.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/flaticon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/gijgo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/animate.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/slicknav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/theme/css/style.css\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css\">\r\n");
      out.write("    \r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		UserModel um = null;
		String role = "", name = "", uid = "";
		boolean isUser = false;
		boolean isAdmin = false;
		boolean isNGO = false;
		if (session.getAttribute("USER_MODEL") != null) {
			um = (UserModel) session.getAttribute("USER_MODEL");
			if (um.getRoleid().equalsIgnoreCase("2")) { // user
				role = "User";
				uid = um.getUserid();
				isUser = true;
			} else if (um.getRoleid().equalsIgnoreCase("1")) {
				role = "NGO";
				uid = um.getUserid();
				isNGO = true;
			} else if (um.getRoleid().equalsIgnoreCase("3")) {
				role = "Administrator";
				uid = um.getUserid();
				isAdmin = true;
			}

		}
	
      out.write("\r\n");
      out.write("\t<div class=\"slider_area \">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"single_slider d-flex align-items-center justify-content-center slider_bg_1\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xl-5 col-lg-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"single_about_info\">\r\n");
      out.write("\t\t\t\t\t\t\t<h1 style=\"font-size:50px\">\r\n");
      out.write("\t\t\t\t\t\t\t\tCradle Of Life\r\n");
      out.write("\t\t\t\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"text-info font-bold\">Every moment counts in the fragile early hours of a\r\n");
      out.write("\t\t\t\t\t\t\t\tnewborn's life. Help us ensure they receive the vital care they\r\n");
      out.write("\t\t\t\t\t\t\t\tneed by donating towards the installation of state-of-the-art\r\n");
      out.write("\t\t\t\t\t\t\t\tbaby incubators. Your generosity can make a life-changing\r\n");
      out.write("\t\t\t\t\t\t\t\tdifference.</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#form_login\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"login popup-with-form genric-btn success circle \">Let's\r\n");
      out.write("\t\t\t\t\t\t\t\tLog In</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-xl-7 col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"slider_info\">\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<h4 class=\"text-dark font-italic\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\"It's not just about funding. </br>It's about belief, momentum, and\r\n");
      out.write("\t\t\t\t\t\t\t\tshared dreams.\"\r\n");
      out.write("\t\t\t\t\t\t\t</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Sign in-->\r\n");
      out.write("\t\t\t\t\t<form id=\"form_login\" class=\"white-popup-block mfp-hide\"\r\n");
      out.write("\t\t\t\t\t\taction=\"javascript:fnSubmit();\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"popup_box \">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"popup_inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"logo text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/img/logo.png\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>Sign in</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" id=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"User Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"boxed_btn_orange\">Sign\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tin</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<p class=\"dont-hav-acc\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\tNot Register? <a class=\"dont-hav-acc\" href=\"#reg_form\">Sign\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tUp</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<!-- form itself end -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--Registration form -->\r\n");
      out.write("\t\t\t\t\t<form id=\"reg_form\" class=\"white-popup-block mfp-hide\"\r\n");
      out.write("\t\t\t\t\t\taction=\"javascript:fnReg();\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"popup_box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"popup_inner\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>Registration</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Role Selection -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12 mb-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"text-dark\">Who are you?:</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select id=\"roleid\" name=\"roleid\" onchange=\"fnData();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"0\">Select Role</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">NGO</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">Donator</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- <option value=\"3\">Admin</option> (for admin to display on screen)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- NGO Form Fields -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"NGOForm\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"ngo\" id=\"ngo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter NGO Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Common Fields for all roles -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"email\" name=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Email\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"address\" id=\"address\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Address\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"phoneno\" id=\"phoneno\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tpattern=\"[0-9]{10}\" title=\"Accepted 10 Digit Only\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Mobile Number\" required=\"required\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- User Form Fields -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"UserForm\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"fname\" id=\"fname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter First Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"lname\" id=\"lname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Last Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"pancardno\" id=\"pancardno\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpattern=\"^[A-Z]{5}\\d{4}[A-Z]{1}$\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ttitle=\"Accepted 10 Digit Only\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter PAN card No.\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Admin Form Fields -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"AdminForm\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"name\" id=\"adminname\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- Common Fields for username and password -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" id=\"username\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Username\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Password\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"cpassword\" id=\"cpassword\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Confirm password\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"font-weight-bold text-center\" id='message'></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-xl-12 d-flex justify-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"boxed_btn_orange\">Sign\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tUp</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- form itself end -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!-- JS here -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/vendor/modernizr-3.5.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/vendor/jquery-1.12.4.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/popper.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/owl.carousel.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/isotope.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/ajax-form.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/waypoints.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.counterup.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/scrollIt.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.scrollUp.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/wow.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/nice-select.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.slicknav.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/plugins.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/gijgo.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--contact js-->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/contact.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.ajaxchimp.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.form.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/mail-script.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/theme/js/main.js\"></script>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('#password, #cpassword').on('keyup', function () {\r\n");
      out.write("\t  if ($('#password').val() == $('#cpassword').val()) {\r\n");
      out.write("\t    $('#message').html('Matching').css('color', 'cyan');\r\n");
      out.write("\t  } else \r\n");
      out.write("\t    $('#message').html('Not Matching').css('color', 'red');\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function fnData() {\r\n");
      out.write("    var selectedRole = document.getElementById(\"roleid\").value;\r\n");
      out.write("\r\n");
      out.write("    // Hide all form sections by default\r\n");
      out.write("    document.getElementById(\"NGOForm\").style.display = \"none\";\r\n");
      out.write("    document.getElementById(\"UserForm\").style.display = \"none\";\r\n");
      out.write("    document.getElementById(\"AdminForm\").style.display = \"none\";\r\n");
      out.write("\r\n");
      out.write("    // Display appropriate form sections based on the selected role\r\n");
      out.write("    if (selectedRole == \"1\") { // NGO\r\n");
      out.write("        document.getElementById(\"NGOForm\").style.display = \"block\";\r\n");
      out.write("    } else if (selectedRole == \"2\") { // Donator/User\r\n");
      out.write("        document.getElementById(\"UserForm\").style.display = \"block\";\r\n");
      out.write("    } else if (selectedRole == \"3\") { // Admin\r\n");
      out.write("        document.getElementById(\"AdminForm\").style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fnSubmit(){\t\r\n");
      out.write("\tvar str = $(\"#form_login\" ).serialize();\r\n");
      out.write("\t//alert(str);\r\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=checkLogin\",str, function(data) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t                    data = $.trim(data);\r\n");
      out.write("\t\t\t\t\t\t\t\tif (data==1) {\t\r\n");
      out.write("\r\n");
      out.write("                               window.location.href = \"");
      out.print(request.getContextPath());
      out.write("/pages/index.jsp\";    \r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t//\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t     \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"Please Enter Valid Credentials\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$('#form_login')[0].reset();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t//registration form\r\n");
      out.write("\tfunction fnReg(){\r\n");
      out.write("\tvar str = $(\"#reg_form\").serialize();\r\n");
      out.write("// \talert(str);\r\n");
      out.write("\t$.post(\"");
      out.print(request.getContextPath());
      out.write("/tiles/ajax.jsp?methodId=registerNewUser\",\r\n");
      out.write("\t\t\t\t\t\tstr, function(data) {\r\n");
      out.write("\t\t\t\t\t\t\tdata = $.trim(data);\r\n");
      out.write("\t\t\t\t\t\t\tif (data==1) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\twindow.location.href=\"");
      out.print(request.getContextPath());
      out.write("/pages/login.jsp\";\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"Error\");\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t$('#reg_form')[0].reset();\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
